n_part: 5000
n_turns: 10000 # in turns
IBS_step: 5 # in turns
ibs_lib_path: /afs/cern.ch/work/e/elwaagaa/public/IBS/IBS_for_Xsuite

# Sequence to load
xsuite_line: /afs/cern.ch/work/e/elwaagaa/public/IBS/IBS_benchmark_for_Xsuite/000_sequences_and_XSlines/SPS_injection_ions/xsuite_line/sps_line_ions_for_tracking.json

energy: 1415.72                           # energy in GeV
bunch_intensity: 350000000000.0
emit_x: 1.2612
emit_y: 0.9081                         # ey in um
sigma_z: 0.01935

V0max: 1.7                       # RF voltage in MV
h: 4653

# Activate the different modes
mode_kinetic: 1
mode_analytical: 1
mode_simple: 0

# Save results
save_to: /eos/user/e/elwaagaa/PhD/Projects/IBS/IBSresults_SPS_injection_ions_bunch_length/064
log_file: /afs/cern.ch/work/e/elwaagaa/public/IBS/IBS_benchmark_for_Xsuite/003_PyIBS_Xsuite_treemaker/SPS_injection_ions_bunch_length/064/tree_maker.log
parent: ./
modes:
- all
